### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by cjohnson8989** [Code-for-Miami/navigatemiami#1]
Simple landing page w/logo and text explaining what Navigate Miami is. Includes button to send email for more information.

### Tasks

- [ ] Design Page 
- [ ] Write Copy
- [ ] Add Google Form to collect emails.
- [ ] Create HTML
- [ ] Create Github Page 
- [ ] Attach Google Analytics #2 
- [ ] Point Domain to Github Page

**Comment by codebycody-zz** [comment]
I put together the first draft of a landing page [here](https://github.com/codebycody/CST).
Its written using bootstrap4 and I will be adding more features to it going forward. But its there and has documentation on how to [add Google Analytics](https://github.com/codebycody/CST/wiki/Set-up-Analytics-tracking-with-gtag.js) to it. I'll work on the documentation for adding email captures next.

**Comment by CyberStrike** [comment]
@codebycody Forked it to here. https://github.com/Code-for-Miami/project-landing-page-template
let me know when you update the readme and I'll merge the upstream.

**Comment by codebycody-zz** [comment]
@CyberStrike You didn't copy the wiki when you forked the project?

**Comment by codebycody-zz** [comment]
Pull request for page is [Here](https://github.com/Code-for-Miami/project-landing-page-template/pull/1)

**Comment by steven-barkley** [comment]
Hello @codebycody @cjohnson8989 I am here as a resource. I’m looking to be involved on small small tasks and learn my way around building projects as I go.

**Comment by CyberStrike** [comment]
@codebycody Copied over your wiki

**Comment by codebycody-zz** [comment]
@steven-barkley Awesome thank you, what area are you interested in helping/learn with this project?

**Comment by steven-barkley** [comment]
QA Testing basics, I believe is my weakest area and when to use DRY methodology.

Sent from my iPhone

On Dec 1, 2017, at 10:33 AM, Cody Michaels <notifications@github.com<mailto:notifications@github.com>> wrote:


@steven-barkley<https://github.com/steven-barkley> Awesome thank you, what area are you interested in helping/learn with this project?

**Comment by codebycody-zz** [comment]
Alright sounds good. Once we get a design decision from the project stakeholders we can start going over those things with you.

**Comment by steven-barkley** [comment]
Gotcha

Sent from my iPhone

On Dec 1, 2017, at 10:42 AM, Cody Michaels <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright sounds good. Once we get a design decision from the project stakeholders we can start going over those things with you.

**Comment by cjohnson8989** [comment]
@codebycody @CyberStrike Hi folks! Steven welcome on board. Thank you for contributing your time and support!!! Chris leads the technical team. I'm learning along the way also. Reviewing items now!
